In [1]:
# ALL THE LIBRARIES AND PACKAGES INSTALLED
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path

In [2]:
pd.set_option("display.max_columns",None) 
pd.set_option("display.max_rows",100)
pd.set_option("display.float_format" ,"{:,.2f}".format)

print("Libraries imported successfully.")

Libraries imported successfully.

In [3]:
# PROJECT PATHS.
PROJECT_ROOT = Path.cwd().parent
RAW_DATA_PATH = PROJECT_ROOT / "data" / "raw"
PROCESSED_DATA_PATH = PROJECT_ROOT / "data" / "processed"
REPORTS_PATH = PROJECT_ROOT / "reports"

print("Project root:", PROJECT_ROOT)
print("Raw data path:", RAW_DATA_PATH)
print("Processed data path:", PROCESSED_DATA_PATH)
print("Reports path:", REPORTS_PATH)

Project root: e:\Learning\Projects\Olist-Ecom
Raw data path: e:\Learning\Projects\Olist-Ecom\data\raw
Processed data path: e:\Learning\Projects\Olist-Ecom\data\processed
Reports path: e:\Learning\Projects\Olist-Ecom\reports

In [4]:
# CONFIRMING THE DATA FILES ARE FOUND
if not RAW_DATA_PATH.exists():
    raise FileNotFoundError("Raw data folder not found: {RAW_DATA_PATH}")
else:
    print("Raw data folder found.")

Raw data folder found.

In [5]:
csvFiles = sorted(RAW_DATA_PATH.glob("*.csv"))
print(f"Number of CSV files found: {len(csvFiles)}")

for file in csvFiles:
    print(file.name)

Number of CSV files found: 9
olist_customers_dataset.csv
olist_geolocation_dataset.csv
olist_order_items_dataset.csv
olist_order_payments_dataset.csv
olist_order_reviews_dataset.csv
olist_orders_dataset.csv
olist_products_dataset.csv
olist_sellers_dataset.csv
product_category_name_translation.csv

In [6]:
# DATASET CONFIGURATION CREATION
DATA_FILES = {
    "customers": "olist_customers_dataset.csv",
    "geolocation": "olist_geolocation_dataset.csv",
    "order_items": "olist_order_items_dataset.csv",
    "order_payments": "olist_order_payments_dataset.csv",
    "order_reviews": "olist_order_reviews_dataset.csv",
    "orders": "olist_orders_dataset.csv",
    "products": "olist_products_dataset.csv",
    "sellers": "olist_sellers_dataset.csv",
    "category_translation": "product_category_name_translation.csv"
}

print("Dataset configuration created.")

Dataset configuration created.

In [7]:
dataset = {}
for name, fileName in DATA_FILES.items():
    filePath = RAW_DATA_PATH / fileName
    if not filePath.exists():
        raise FileNotFoundError("Missing File {filePath}")
    dataset[name] = pd.read_csv(filePath)
    
print("All datasets loaded Successfully!!!")

All datasets loaded Successfully!!!

In [62]:
dataset

{'customers':                             customer_id                customer_unique_id  \
 0      06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
 1      18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
 2      4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
 3      b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
 4      4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066
 ...                                 ...                               ...
 99436  17ddf5dd5d51696bb3d7c6291687be6f  1a29b476fee25c95fbafc67c5ac95cf8
 99437  e7b71a9017aa05c9a7fd292d714858e8  d52a67c98be1cf6a5c84435bd38d095d
 99438  5e28dfe12db7fb50a4b2f691faecea5e  e9f50caf99f032f0bf3c55141f019d99
 99439  56b18e2166679b8a959d72dd06da27f9  73c2643a0a458b49f58cea58833b192e
 99440  274fa6071e5e17fe303b9748641082c8  84732c5050c01db9b23e19ba39899398

        customer_zip_code_prefix          customer_city customer_state
 0                         14409                 franca             SP
 1                          9790  sao bernardo do campo             SP
 2                          1151              sao paulo             SP
 3                          8775        mogi das cruzes             SP
 4                         13056               campinas             SP
 ...                         ...                    ...            ...
 99436                      3937              sao paulo             SP
 99437                      6764        taboao da serra             SP
 99438                     60115              fortaleza             CE
 99439                     92120                 canoas             RS
 99440                      6703                  cotia             SP

 [99441 rows x 5 columns],
 'geolocation':          geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
 0                               1037           -23.55           -46.64
 1                               1046           -23.55           -46.64
 2                               1046           -23.55           -46.64
 3                               1041           -23.54           -46.64
 4                               1035           -23.54           -46.64
 ...                              ...              ...              ...
 1000158                        99950           -28.07           -52.01
 1000159                        99900           -27.88           -52.22
 1000160                        99950           -28.07           -52.01
 1000161                        99980           -28.39           -51.85
 1000162                        99950           -28.07           -52.02

         geolocation_city geolocation_state
 0              sao paulo                SP
 1              sao paulo                SP
 2              sao paulo                SP
 3              sao paulo                SP
 4              sao paulo                SP
 ...                  ...               ...
 1000158         tapejara                RS
 1000159   getulio vargas                RS
 1000160         tapejara                RS
 1000161  david canabarro                RS
 1000162         tapejara                RS

 [1000163 rows x 5 columns],
 'order_items':                                 order_id  order_item_id  \
 0       00010242fe8c5a6d1ba2dd792cb16214              1
 1       00018f77f2f0320c557190d7a144bdd3              1
 2       000229ec398224ef6ca0657da4fc703e              1
 3       00024acbcdf0a6daa1e931b038114c75              1
 4       00042b26cf59d7ce69dfabb4e55b4fd9              1
 ...                                  ...            ...
 112645  fffc94f6ce00a00581880bf54a75a037              1
 112646  fffcd46ef2263f404302a634eb57f7eb              1
 112647  fffce4705a9662cd70adb13d4a31832d              1
 112648  fffe18544ffabc95dfada21779c9644f              1
 112649  fffe41c64501cc87c801fd61db3f6244              1

                               product_id                         seller_id  \
 0       4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202
 1       e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36
 2       c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d
 3       7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4
 4       ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87
 ...                                  ...                               ...
 112645  4aa6014eceb682077f9dc4bffebc05b0  b8bc237ba3788b23da09c0f1f3a3288c
 112646  32e07fd915822b0765e448c4dd74c828  f3c38ab652836d21de61fb8314b69182
 112647  72a30483855e2eafc67aee5dc2560482  c3cfdc648177fdbbbb35635a37472c53
 112648  9c422a519119dcad7575db5af1ba540e  2b3e4a2a3ea8e01938cabda2a3e5cc79
 112649  350688d9dc1e75ff97be326363655e01  f7ccf836d21b2fb1de37564105216cc1

         shipping_limit_date  price  freight_value
 0       2017-09-19 09:45:35  58.90          13.29
 1       2017-05-03 11:05:13 239.90          19.93
 2       2018-01-18 14:48:30 199.00          17.87
 3       2018-08-15 10:10:18  12.99          12.79
 4       2017-02-13 13:57:51 199.90          18.14
 ...                     ...    ...            ...
 112645  2018-05-02 04:11:01 299.99          43.41
 112646  2018-07-20 04:31:48 350.00          36.53
 112647  2017-10-30 17:14:25  99.90          16.95
 112648  2017-08-21 00:04:32  55.99           8.72
 112649  2018-06-12 17:10:13  43.00          12.79

 [112650 rows x 7 columns],
 'order_payments':                                 order_id  payment_sequential payment_type  \
 0       b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
 1       a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card
 2       25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card
 3       ba78997921bbcdc1373bb41e913ab953                   1  credit_card
 4       42fdf880ba16b47b59251dd489d4441a                   1  credit_card
 ...                                  ...                 ...          ...
 103881  0406037ad97740d563a178ecc7a2075c                   1       boleto
 103882  7b905861d7c825891d6347454ea7863f                   1  credit_card
 103883  32609bbb3dd69b3c066a6860554a77bf                   1  credit_card
 103884  b8b61059626efa996a60be9bb9320e10                   1  credit_card
 103885  28bbae6599b09d39ca406b747b6632b1                   1       boleto

         payment_installments  payment_value
 0                          8          99.33
 1                          1          24.39
 2                          1          65.71
 3                          8         107.78
 4                          2         128.45
 ...                      ...            ...
 103881                     1         363.31
 103882                     2          96.80
 103883                     1          47.77
 103884                     5         369.54
 103885                     1         191.58

 [103886 rows x 5 columns],
 'order_reviews':                               review_id                          order_id  \
 0      7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
 1      80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33
 2      228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b
 3      e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b
 4      f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1
 ...                                 ...                               ...
 99219  574ed12dd733e5fa530cfd4bbf39d7c9  2a8c23fee101d4d5662fa670396eb8da
 99220  f3897127253a9592a73be9bdfdf4ed7a  22ec9f0669f784db00fa86d035cf8602
 99221  b3de70c89b1510c4cd3d0649fd302472  55d4004744368f5571d1f590031933e4
 99222  1adeb9d84d72fe4e337617733eb85149  7725825d039fc1f0ceb7635e3f7d9206
 99223  efe49f1d6f951dd88b51e6ccd4cc548f  90531360ecb1eec2a1fbb265a0db0508

        review_score review_comment_title  \
 0                 4                  NaN
 1                 5                  NaN
 2                 5                  NaN
 3                 5                  NaN
 4                 5                  NaN
 ...             ...                  ...
 99219             5                  NaN
 99220             5                  NaN
 99221             5                  NaN
 99222             4                  NaN
 99223             1                  NaN

                                   review_comment_message review_creation_date  \
 0                                                    NaN  2018-01-18 00:00:00
 1                                                    NaN  2018-03-10 00:00:00
 2                                                    NaN  2018-02-17 00:00:00
 3                  Recebi bem antes do prazo estipulado.  2017-04-21 00:00:00
 4      Parabéns lojas lannister adorei comprar pela I...  2018-03-01 00:00:00
 ...                                                  ...                  ...
 99219                                                NaN  2018-07-07 00:00:00
 99220                                                NaN  2017-12-09 00:00:00
 99221  Excelente mochila, entrega super rápida. Super...  2018-03-22 00:00:00
 99222                                                NaN  2018-07-01 00:00:00
 99223  meu produto chegou e ja tenho que devolver, po...  2017-07-03 00:00:00

       review_answer_timestamp
 0         2018-01-18 21:46:59
 1         2018-03-11 03:05:13
 2         2018-02-18 14:36:24
 3         2017-04-21 22:02:06
 4         2018-03-02 10:26:53
 ...                       ...
 99219     2018-07-14 17:18:30
 99220     2017-12-11 20:06:42
 99221     2018-03-23 09:10:43
 99222     2018-07-02 12:59:13
 99223     2017-07-03 21:01:49

 [99224 rows x 7 columns],
 'orders':                                order_id                       customer_id  \
 0      e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
 1      53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
 2      47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
 3      949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
 4      ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c
 ...                                 ...                               ...
 99436  9c5dedf39a927c1b2549525ed64a053c  39bd1228ee8140590ac3aca26f2dfe00
 99437  63943bddc261676b46f01ca7ac2f7bd8  1fca14ff2861355f6e5f14306ff977a7
 99438  83c1379a015df1e13d02aae0204711ab  1aa71eb042121263aafbe80c1b562c9c
 99439  11c177c8e97725db2631073c19f07b62  b331b74b18dc79bcdf6532d51e1637c1
 99440  66dea50a8b16d9b4dee7af250b4be1a5  edb027a75a1449115f6b43211ae02a24

       order_status order_purchase_timestamp    order_approved_at  \
 0        delivered      2017-10-02 10:56:33  2017-10-02 11:07:15
 1        delivered      2018-07-24 20:41:37  2018-07-26 03:24:27
 2        delivered      2018-08-08 08:38:49  2018-08-08 08:55:23
 3        delivered      2017-11-18 19:28:06  2017-11-18 19:45:59
 4        delivered      2018-02-13 21:18:39  2018-02-13 22:20:29
 ...            ...                      ...                  ...
 99436    delivered      2017-03-09 09:54:05  2017-03-09 09:54:05
 99437    delivered      2018-02-06 12:58:58  2018-02-06 13:10:37
 99438    delivered      2017-08-27 14:46:43  2017-08-27 15:04:16
 99439    delivered      2018-01-08 21:28:27  2018-01-08 21:36:21
 99440    delivered      2018-03-08 20:57:30  2018-03-09 11:20:28

       order_delivered_carrier_date order_delivered_customer_date  \
 0              2017-10-04 19:55:00           2017-10-10 21:25:13
 1              2018-07-26 14:31:00           2018-08-07 15:27:45
 2              2018-08-08 13:50:00           2018-08-17 18:06:29
 3              2017-11-22 13:39:59           2017-12-02 00:28:42
 4              2018-02-14 19:46:34           2018-02-16 18:17:02
 ...                            ...                           ...
 99436          2017-03-10 11:18:03           2017-03-17 15:08:01
 99437          2018-02-07 23:22:42           2018-02-28 17:37:56
 99438          2017-08-28 20:52:26           2017-09-21 11:24:17
 99439          2018-01-12 15:35:03           2018-01-25 23:32:54
 99440          2018-03-09 22:11:59           2018-03-16 13:08:30

       order_estimated_delivery_date
 0               2017-10-18 00:00:00
 1               2018-08-13 00:00:00
 2               2018-09-04 00:00:00
 3               2017-12-15 00:00:00
 4               2018-02-26 00:00:00
 ...                             ...
 99436           2017-03-28 00:00:00
 99437           2018-03-02 00:00:00
 99438           2017-09-27 00:00:00
 99439           2018-02-15 00:00:00
 99440           2018-04-03 00:00:00

 [99441 rows x 8 columns],
 'products':                              product_id              product_category_name  \
 0      1e9e8ef04dbcff4541ed26657ea517e5                         perfumaria
 1      3aa071139cb16b67ca9e5dea641aaa2f                              artes
 2      96bd76ec8810374ed1b65e291975717f                      esporte_lazer
 3      cef67bcfe19066a932b7673e239eb23d                              bebes
 4      9dc1a7de274444849c219cff195d0b71              utilidades_domesticas
 ...                                 ...                                ...
 32946  a0b7d5a992ccda646f2d34e418fff5a0                   moveis_decoracao
 32947  bf4538d88321d0fd4412a93c974510e6  construcao_ferramentas_iluminacao
 32948  9a7c6041fa9592d9d9ef6cfe62a71f8c                    cama_mesa_banho
 32949  83808703fc0706a22e264b9d75f04a2e             informatica_acessorios
 32950  106392145fca363410d287a815be6de4                    cama_mesa_banho

        product_name_lenght  product_description_lenght  product_photos_qty  \
 0                    40.00                      287.00                1.00
 1                    44.00                      276.00                1.00
 2                    46.00                      250.00                1.00
 3                    27.00                      261.00                1.00
 4                    37.00                      402.00                4.00
 ...                    ...                         ...                 ...
 32946                45.00                       67.00                2.00
 32947                41.00                      971.00                1.00
 32948                50.00                      799.00                1.00
 32949                60.00                      156.00                2.00
 32950                58.00                      309.00                1.00

        product_weight_g  product_length_cm  product_height_cm  \
 0                225.00              16.00              10.00
 1              1,000.00              30.00              18.00
 2                154.00              18.00               9.00
 3                371.00              26.00               4.00
 4                625.00              20.00              17.00
 ...                 ...                ...                ...
 32946         12,300.00              40.00              40.00
 32947          1,700.00              16.00              19.00
 32948          1,400.00              27.00               7.00
 32949            700.00              31.00              13.00
 32950          2,083.00              12.00               2.00

        product_width_cm
 0                 14.00
 1                 20.00
 2                 15.00
 3                 26.00
 4                 13.00
 ...                 ...
 32946             40.00
 32947             16.00
 32948             27.00
 32949             20.00
 32950              7.00

 [32951 rows x 9 columns],
 'sellers':                              seller_id  seller_zip_code_prefix  \
 0     3442f8959a84dea7ee197c632cb2df15                   13023
 1     d1b65fc7debc3361ea86b5f14c68d2e2                   13844
 2     ce3ad9de960102d0677a81f5d0bb7b2d                   20031
 3     c0f3eea2e14555b6faeea3dd58c1b1c3                    4195
 4     51a04a8a6bdcb23deccc82b0b80742cf                   12914
 ...                                ...                     ...
 3090  98dddbc4601dd4443ca174359b237166                   87111
 3091  f8201cab383e484733266d1906e2fdfa                   88137
 3092  74871d19219c7d518d0090283e03c137                    4650
 3093  e603cf3fec55f8697c9059638d6c8eb5                   96080
 3094  9e25199f6ef7e7c347120ff175652c3b                   12051

             seller_city seller_state
 0              campinas           SP
 1            mogi guacu           SP
 2        rio de janeiro           RJ
 3             sao paulo           SP
 4     braganca paulista           SP
 ...                 ...          ...
 3090            sarandi           PR
 3091            palhoca           SC
 3092          sao paulo           SP
 3093            pelotas           RS
 3094            taubate           SP

 [3095 rows x 4 columns],
 'category_translation':                              product_category_name  \
 0                                     beleza_saude
 1                           informatica_acessorios
 2                                       automotivo
 3                                  cama_mesa_banho
 4                                 moveis_decoracao
 5                                    esporte_lazer
 6                                       perfumaria
 7                            utilidades_domesticas
 8                                        telefonia
 9                               relogios_presentes
 10                               alimentos_bebidas
 11                                           bebes
 12                                       papelaria
 13                        tablets_impressao_imagem
 14                                      brinquedos
 15                                  telefonia_fixa
 16                              ferramentas_jardim
 17                     fashion_bolsas_e_acessorios
 18                                 eletroportateis
 19                                  consoles_games
 20                                           audio
 21                                fashion_calcados
 22                                      cool_stuff
 23                                malas_acessorios
 24                                    climatizacao
 25               construcao_ferramentas_construcao
 26  moveis_cozinha_area_de_servico_jantar_e_jardim
 27                   construcao_ferramentas_jardim
 28                         fashion_roupa_masculina
 29                                        pet_shop
 30                               moveis_escritorio
 31                                    market_place
 32                                     eletronicos
 33                                eletrodomesticos
 34                               artigos_de_festas
 35                                   casa_conforto
 36              construcao_ferramentas_ferramentas
 37                       agro_industria_e_comercio
 38                       moveis_colchao_e_estofado
 39                                 livros_tecnicos
 40                                 casa_construcao
 41                           instrumentos_musicais
 42                                     moveis_sala
 43               construcao_ferramentas_iluminacao
 44                   industria_comercio_e_negocios
 45                                       alimentos
 46                                           artes
 47                                   moveis_quarto
 48                          livros_interesse_geral
 49                construcao_ferramentas_seguranca
 50                  fashion_underwear_e_moda_praia
 51                                 fashion_esporte
 52                         sinalizacao_e_seguranca
 53                                             pcs
 54                                artigos_de_natal
 55                          fashion_roupa_feminina
 56                              eletrodomesticos_2

In [8]:
# x----- SHAPE OF THE DATASETS-------x
datasetShape = []
for name, df in dataset.items():
    datasetShape.append({
        "dataset": name,
        "rows": df.shape[0],
        "columns": df.shape[1]    
        }
    )
# datasetShape
shapeDF = pd.DataFrame(datasetShape)
shapeDF

                dataset     rows  columns
0             customers    99441        5
1           geolocation  1000163        5
2           order_items   112650        7
3        order_payments   103886        5
4         order_reviews    99224        7
5                orders    99441        8
6              products    32951        9
7               sellers     3095        4
8  category_translation       71        2

In [9]:
# x------------- DATA TYPES OF THE DATASET ---------------x

for name, df in dataset.items():
    print("-"*30)
    print(name.upper())
    print(df.dtypes)

------------------------------
CUSTOMERS
customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object
------------------------------
GEOLOCATION
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                   str
geolocation_state                  str
dtype: object
------------------------------
ORDER_ITEMS
order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object
------------------------------
ORDER_PAYMENTS
order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object
------------------------------
ORDER_REVIEWS
review_id                    str
order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
dtype: object
------------------------------
ORDERS
order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object
------------------------------
PRODUCTS
product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object
------------------------------
SELLERS
seller_id                   str
seller_zip_code_prefix    int64
seller_city                 str
seller_state                str
dtype: object
------------------------------
CATEGORY_TRANSLATION
product_category_name            str
product_category_name_english    str
dtype: object

In [10]:
# x----------- DATA DICTIONARY ---------------X

dataDictionary = []
for name, df in dataset.items():
    for col in df:
        dataDictionary.append({
                'dataset': name,
                'columns': col,
                'dataType': str(df[col].dtypes),
                'count': len(df[col]),
                'missingValues': df[col].isna().sum(),
                'missingPercentage': (df[col].isna().mean() * 100).round(2),
                'uniqueValues': (df[col].nunique(dropna = True))
            })
# dataDictionary
dataDictionaryDF = pd.DataFrame(dataDictionary)
dataDictionaryDF

,dataset,columns,dataType,count,missingValues,missingPercentage,uniqueValues
0,customers,customer_id,str,99441,0,0.00,99441
1,customers,customer_unique_id,str,99441,0,0.00,96096
2,customers,customer_zip_code_prefix,int64,99441,0,0.00,14994
3,customers,customer_city,str,99441,0,0.00,4119
4,customers,customer_state,str,99441,0,0.00,27
5,geolocation,geolocation_zip_code_prefix,int64,1000163,0,0.00,19015
6,geolocation,geolocation_lat,float64,1000163,0,0.00,717360
7,geolocation,geolocation_lng,float64,1000163,0,0.00,717613
8,geolocation,geolocation_city,str,1000163,0,0.00,8011
9,geolocation,geolocation_state,str,1000163,0,0.00,27
10,order_items,order_id,str,112650,0,0.00,98666
11,order_items,order_item_id,int64,112650,0,0.00,21
12,order_items,product_id,str,112650,0,0.00,32951
13,order_items,seller_id,str,112650,0,0.00,3095
14,order_items,shipping_limit_date,str,112650,0,0.00,93318
15,order_items,price,float64,112650,0,0.00,5968
16,order_items,freight_value,float64,112650,0,0.00,6999
17,order_payments,order_id,str,103886,0,0.00,99440
18,order_payments,payment_sequential,int64,103886,0,0.00,29
19,order_payments,payment_type,str,103886,0,0.00,5
20,order_payments,payment_installments,int64,103886,0,0.00,24
21,order_payments,payment_value,float64,103886,0,0.00,29077
22,order_reviews,review_id,str,99224,0,0.00,98410
23,order_reviews,order_id,str,99224,0,0.00,98673
24,order_reviews,review_score,int64,99224,0,0.00,5
25,order_reviews,review_comment_title,str,99224,87656,88.34,4527
26,order_reviews,review_comment_message,str,99224,58247,58.70,36159
27,order_reviews,review_creation_date,str,99224,0,0.00,636
28,order_reviews,review_answer_timestamp,str,99224,0,0.00,98248
29,orders,order_id,str,99441,0,0.00,99441
30,orders,customer_id,str,99441,0,0.00,99441
31,orders,order_status,str,99441,0,0.00,8
32,orders,order_purchase_timestamp,str,99441,0,0.00,98875
33,orders,order_approved_at,str,99441,160,0.16,90733
34,orders,order_delivered_carrier_date,str,99441,1783,1.79,81018
35,orders,order_delivered_customer_date,str,99441,2965,2.98,95664
36,orders,order_estimated_delivery_date,str,99441,0,0.00,459
37,products,product_id,str,32951,0,0.00,32951
38,products,product_category_name,str,32951,610,1.85,73
39,products,product_name_lenght,float64,32951,610,1.85,66
40,products,product_description_lenght,float64,32951,610,1.85,2960
41,products,product_photos_qty,float64,32951,610,1.85,19
42,products,product_weight_g,float64,32951,2,0.01,2204
43,products,product_length_cm,float64,32951,2,0.01,99
44,products,product_height_cm,float64,32951,2,0.01,102
45,products,product_width_cm,float64,32951,2,0.01,95
46,sellers,seller_id,str,3095,0,0.00,3095
47,sellers,seller_zip_code_prefix,int64,3095,0,0.00,2246
48,sellers,seller_city,str,3095,0,0.00,611
49,sellers,seller_state,str,3095,0,0.00,23
50,category_translation,product_category_name,str,71,0,0.00,71
51,category_translation,product_category_name_english,str,71,0,0.00,71

In [11]:
# ---------- CHECKING MISSINGS ----------
missingSummary = []

for name, df in dataset.items():
    for column in df.columns:
        missingSummary.append({
            "dataset": name,
            "column": column,
            "missingCount": df[column].isna().sum(),
            "missingPercentage": (df[column].isna().mean() * 100).round(2)
        })

missingDF = pd.DataFrame(missingSummary)

missingDF = missingDF[
    missingDF["missingCount"] > 0
].sort_values(
    "missingPercentage",
    ascending=False
)

missingDF

,dataset,column,missingCount,missingPercentage
25,order_reviews,review_comment_title,87656,88.34
26,order_reviews,review_comment_message,58247,58.70
35,orders,order_delivered_customer_date,2965,2.98
39,products,product_name_lenght,610,1.85
38,products,product_category_name,610,1.85
40,products,product_description_lenght,610,1.85
41,products,product_photos_qty,610,1.85
34,orders,order_delivered_carrier_date,1783,1.79
33,orders,order_approved_at,160,0.16
42,products,product_weight_g,2,0.01
43,products,product_length_cm,2,0.01
44,products,product_height_cm,2,0.01
45,products,product_width_cm,2,0.01

In [12]:
missingColumnsList = []
count = 0
for data in missingSummary:
    for name, value in data.items():
        # print()
        if name == 'missingCount':
            if data[name] > 0:
                missingColumnsList.append(data['column'])
                print(f"Column {data['column']} added successfully!!")
                count = count + 1
print(f"{count} Missing Columns are added successfully!")

Column review_comment_title added successfully!!
Column review_comment_message added successfully!!
Column order_approved_at added successfully!!
Column order_delivered_carrier_date added successfully!!
Column order_delivered_customer_date added successfully!!
Column product_category_name added successfully!!
Column product_name_lenght added successfully!!
Column product_description_lenght added successfully!!
Column product_photos_qty added successfully!!
Column product_weight_g added successfully!!
Column product_length_cm added successfully!!
Column product_height_cm added successfully!!
Column product_width_cm added successfully!!
13 Missing Columns are added successfully!

In [13]:
missingColumnsList

['review_comment_title',
 'review_comment_message',
 'order_approved_at',
 'order_delivered_carrier_date',
 'order_delivered_customer_date',
 'product_category_name',
 'product_name_lenght',
 'product_description_lenght',
 'product_photos_qty',
 'product_weight_g',
 'product_length_cm',
 'product_height_cm',
 'product_width_cm']

In [58]:
missingSummaryDF = pd.DataFrame(missingSummary)

In [66]:
# Numeric Profiling
numericProfile = []
for name, df in dataset.items():
    numericColumns = df.select_dtypes(
        include=np.number
    ).columns
    for column in numericColumns:
        numericProfile.append({
            "dataset": name,
            "column": column,
            "count": df[column].count(),
            "missing": df[column].isna().sum(),
            "min": df[column].min(),
            "max": df[column].max(),
            "mean": df[column].mean(),
            "median": df[column].median(),
            "std": df[column].std(),
            "q25": df[column].quantile(0.25),
            "q75": df[column].quantile(0.75)
        })

numericProfile = pd.DataFrame(
    numericProfile
)

numericProfile

,dataset,column,count,missing,min,max,mean,median,std,q25,q75
0,customers,customer_zip_code_prefix,99441,0,"1,003.00","99,990.00","35,137.47","24,416.00","29,797.94","11,347.00","58,900.00"
1,geolocation,geolocation_zip_code_prefix,1000163,0,"1,001.00","99,990.00","36,574.17","26,530.00","30,549.34","11,075.00","63,504.00"
2,geolocation,geolocation_lat,1000163,0,-36.61,45.07,-21.18,-22.92,5.72,-23.60,-19.98
3,geolocation,geolocation_lng,1000163,0,-101.47,121.11,-46.39,-46.64,4.27,-48.57,-43.77
4,order_items,order_item_id,112650,0,1.00,21.00,1.20,1.00,0.71,1.00,1.00
5,order_items,price,112650,0,0.85,"6,735.00",120.65,74.99,183.63,39.90,134.90
6,order_items,freight_value,112650,0,0.00,409.68,19.99,16.26,15.81,13.08,21.15
7,order_payments,payment_sequential,103886,0,1.00,29.00,1.09,1.00,0.71,1.00,1.00
8,order_payments,payment_installments,103886,0,0.00,24.00,2.85,1.00,2.69,1.00,4.00
9,order_payments,payment_value,103886,0,0.00,"13,664.08",154.10,100.00,217.49,56.79,171.84
10,order_reviews,review_score,99224,0,1.00,5.00,4.09,5.00,1.35,4.00,5.00
11,products,product_name_lenght,32341,610,5.00,76.00,48.48,51.00,10.25,42.00,57.00
12,products,product_description_lenght,32341,610,4.00,"3,992.00",771.50,595.00,635.12,339.00,972.00
13,products,product_photos_qty,32341,610,1.00,20.00,2.19,1.00,1.74,1.00,3.00
14,products,product_weight_g,32949,2,0.00,"40,425.00","2,276.47",700.00,"4,282.04",300.00,"1,900.00"
15,products,product_length_cm,32949,2,7.00,105.00,30.82,25.00,16.91,18.00,38.00
16,products,product_height_cm,32949,2,2.00,105.00,16.94,13.00,13.64,8.00,21.00
17,products,product_width_cm,32949,2,6.00,118.00,23.20,20.00,12.08,15.00,30.00
18,sellers,seller_zip_code_prefix,3095,0,"1,001.00","99,730.00","32,291.06","14,940.00","32,713.45","7,093.50","64,552.50"

In [14]:
#------ DUPLICATE IN KEYS CHECKING -----------X
PRIMARY_KEYS = {
    "orders": ["order_id"],
    "customers": ["customer_id"],
    "products": ["product_id"],
    "sellers": ["seller_id"],
    'test': None,
    "order_items": ["order_id", "order_item_id"],
    "order_payments": ["order_id", "payment_sequential"],
    "order_reviews": ["order_id","review_id"],
    "category_translation": ["product_category_name"],
    "geolocation": None
}

for name, keyCol in PRIMARY_KEYS.items():
    if keyCol is None:
        continue
    df = dataset[name]
    duplicateKey = df.duplicated(
        subset = keyCol
    ).sum()
    print(
        f"{name}: "
        f"{duplicateKey} duplicate primary-key combinations"
    )

orders: 0 duplicate primary-key combinations
customers: 0 duplicate primary-key combinations
products: 0 duplicate primary-key combinations
sellers: 0 duplicate primary-key combinations
order_items: 0 duplicate primary-key combinations
order_payments: 0 duplicate primary-key combinations
order_reviews: 0 duplicate primary-key combinations
category_translation: 0 duplicate primary-key combinations

Order Profiling

In [15]:
# ---------- ORDER PROFILING -------------
order = dataset['orders']
order.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [16]:
order.groupby('order_status')[[
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]].apply(lambda x: x.isna().sum())

,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
order_status,,,,
approved,0,2,2,0
canceled,141,550,619,0
created,5,5,5,0
delivered,14,2,8,0
invoiced,0,314,314,0
processing,0,301,301,0
shipped,0,0,1107,0
unavailable,0,609,609,0

In [17]:
missingDeliveryDate = (order.loc[(order['order_status']=='delivered') & 
                        order['order_delivered_customer_date'].isna()])

print(f"Anomolies: {len(missingDeliveryDate)} Missing Delivery Date in Delivered Orders")

Anomolies: 8 Missing Delivery Date in Delivered Orders

In [18]:
deliveredMask = (
    (order['order_status']=='delivered') &
    (order['order_delivered_customer_date'].notna())
)

print(f"Delivered Orders: {deliveredMask.sum()}")

Delivered Orders: 96470

In [20]:
dateColumns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

def dateMinMax(df ,columns):
    for col in columns:
        print(f"{col} Minimum {df[col].min()}")
        print(f"{col} Maximum {df[col].max()}")

dateMinMax(order,dateColumns)

order_purchase_timestamp Minimum 2016-09-04 21:15:19
order_purchase_timestamp Maximum 2018-10-17 17:30:18
order_approved_at Minimum 2016-09-15 12:16:38
order_approved_at Maximum 2018-09-03 17:40:06
order_delivered_carrier_date Minimum 2016-10-08 10:34:01
order_delivered_carrier_date Maximum 2018-09-11 19:48:28
order_delivered_customer_date Minimum 2016-10-11 13:46:32
order_delivered_customer_date Maximum 2018-10-17 13:22:46
order_estimated_delivery_date Minimum 2016-09-30 00:00:00
order_estimated_delivery_date Maximum 2018-11-12 00:00:00

Customer Profiling

In [21]:
# ---------- CUSTOMER PROFILING -----------
customer = dataset['customers']
customer.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [22]:
print(f"Customer Shape {customer.shape}")
print(f"Customer Columns {customer.columns}")
print("Unique customer IDs:", customer["customer_unique_id"].nunique())
print("Customer IDs:", customer["customer_id"].nunique())

customerOrderCounts = (
    customer["customer_unique_id"]
    .value_counts()
)

Customer Shape (99441, 5)
Customer Columns Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='str')
Unique customer IDs: 96096
Customer IDs: 99441

In [23]:
customerOrderCounts = (
    customer["customer_unique_id"]
    .value_counts()
)

customerOrderCounts

customer_unique_id
8d50f5eadf50201ccdcedfb9e2ac8455    17
3e43e6105506432c953e165fb2acf44c     9
1b6c7548a2a1f9037c1fd3ddfed95f33     7
6469f99c1f9dfae7733b25662e7f1782     7
ca77025e7201e3b30c44b472ff346268     7
                                    ..
1a29b476fee25c95fbafc67c5ac95cf8     1
d52a67c98be1cf6a5c84435bd38d095d     1
e9f50caf99f032f0bf3c55141f019d99     1
73c2643a0a458b49f58cea58833b192e     1
84732c5050c01db9b23e19ba39899398     1
Name: count, Length: 96096, dtype: int64

In [24]:
(customerOrderCounts > 1).sum()

np.int64(2997)

In [25]:
# Does every `customer_id` in Order exist in Customers
order['customer_id'].isin(customer['customer_id']).value_counts()

customer_id
True    99441
Name: count, dtype: int64

Order Item Profiling

In [36]:
# ----------- ORDER ITEM PROFILING
orderItems = dataset['order_items']
orderItems.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [37]:
print('OrderItem - Order Id: Duplicated:', orderItems['order_id'].duplicated().sum())
print('OrderItem - OrderItemId: Duplicated:', orderItems['order_item_id'].duplicated().sum())
print('Total Data: ', len(orderItems))

OrderItem - Order Id: Duplicated: 13984
OrderItem - OrderItemId: Duplicated: 112629
Total Data:  112650

In [38]:
orderItems.duplicated(
    subset=['order_id', 'order_item_id']
).sum()

np.int64(0)

In [39]:
orderItems.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='str')

In [40]:
orderItems.dtypes

order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

In [41]:
print('Price == 0:',(orderItems["price"] == 0).sum())
print('freight value < 0:',(orderItems["freight_value"] < 0).sum())

Price == 0: 0
freight value < 0: 0

In [42]:
orderItems["order_id"].isin(order["order_id"]).value_counts()

order_id
True    112650
Name: count, dtype: int64

In [43]:
orderWithoutItem = order[~order['order_id'].isin(orderItems['order_id'])]
len(orderWithoutItem)

775

In [44]:
itemsPerOrder = (
    orderItems.groupby("order_id")["order_item_id"]
    .count()
)

itemsPerOrder

order_id
00010242fe8c5a6d1ba2dd792cb16214    1
00018f77f2f0320c557190d7a144bdd3    1
000229ec398224ef6ca0657da4fc703e    1
00024acbcdf0a6daa1e931b038114c75    1
00042b26cf59d7ce69dfabb4e55b4fd9    1
                                   ..
fffc94f6ce00a00581880bf54a75a037    1
fffcd46ef2263f404302a634eb57f7eb    1
fffce4705a9662cd70adb13d4a31832d    1
fffe18544ffabc95dfada21779c9644f    1
fffe41c64501cc87c801fd61db3f6244    1
Name: order_item_id, Length: 98666, dtype: int64

In [45]:
orderItems.loc[(orderItems['order_id']=="3a213fcdfe7d98be74ea0dc05a8b31ae"),['price']]

       price
25564 108.00
25565 108.00
25566 108.00
25567 108.00
25568 108.00
25569 108.00
25570 108.00
25571 108.00
25572 108.00
25573 108.00
25574 108.00
25575 108.00

Product Profiling

In [46]:
products = dataset["products"]

products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.00,287.00,1.00,225.00,16.00,10.00,14.00
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.00,276.00,1.00,"1,000.00",30.00,18.00,20.00
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.00,250.00,1.00,154.00,18.00,9.00,15.00
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.00,261.00,1.00,371.00,26.00,4.00,26.00
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.00,402.00,4.00,625.00,20.00,17.00,13.00

In [47]:
products.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='str')

In [48]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

Reviews Profiling

In [49]:
# ----------- REVIEWS PROFILING -----------
reviews = dataset["order_reviews"]
reviews
# dataset.keys()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53
...,...,...,...,...,...,...,...
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN,NaN,2018-07-07 00:00:00,2018-07-14 17:18:30
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN,NaN,2017-12-09 00:00:00,2017-12-11 20:06:42
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,NaN,"Excelente mochila, entrega super rápida. Super...",2018-03-22 00:00:00,2018-03-23 09:10:43
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,NaN,2018-07-01 00:00:00,2018-07-02 12:59:13
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",2017-07-03 00:00:00,2017-07-03 21:01:49

In [50]:
reviews.columns

Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='str')

In [51]:

invalidReviews = reviews[
    ~reviews["review_score"].between(1, 5)
]

print("Invalid review scores:", len(invalidReviews))

Invalid review scores: 0

Payment Profiling

In [52]:
# ----------- PAYMENT PROFILING --------------
payments = dataset["order_payments"]

payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [53]:
payments.duplicated(
    subset = ['order_id','payment_sequential']
).sum()

np.int64(0)

In [54]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

Seller Profiling

In [56]:
# ------------ SELLER PROFILING -----------
sellers = dataset["sellers"]

print(f"Total number of Sellers {len(sellers)}")
print(sellers.info())

Total number of Sellers 3095
<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB
None

In [57]:
sellers.dtypes

seller_id                   str
seller_zip_code_prefix    int64
seller_city                 str
seller_state                str
dtype: object